fix: npe when loading model
java.lang.NullPointerException: Cannot read field "size" because "group" is null
at net.mgsx.gltf.loaders.shared.geometry.MeshSpliter.split(MeshSpliter.java:122)